### ISSUE TITLE
Create a detailed Video walkthrough for GMP

### ISSUE THREAD

**Issue by 0x1100010010** [Analog-Labs/analog-gmp#6]
**Description**

Create a video walkthrough for the general audience interested in understanding GMP mechanisms, clearly distinguishing the differences from other protocols, i.e. smart contract performance improvements, embedded assembly, Gasfee comparison, etc

 - [ ] Gateway walkthrough
 - [ ] GMP usage exemple

**Comment by Lohann** [comment]
The video was published here:
https://www.youtube.com/watch?v=s7y4KJlR_ls
